# forecast configuration

n_en: 100  # number of ensembles
start: '1980-01-01'
stop: '2020-07-31'

#  see 4_pb_model/notes/model_variable_description.txt for output variable details
sntemp_output: ['seg_rain', 'seg_tave_air', 'seg_tave_water', 'seg_outflow', 'seg_tave_gw',
'seg_tave_sroff', 'seg_tave_ss', 'seg_tave_upstream', 'seg_upstream_inflow', 'seginc_gwflow',
'seginc_potet', 'seginc_sroff', 'seginc_ssflow', 'seginc_swrad', 'seg_humid', 'seg_shade', 'seg_ccov', 'seg_width']


orig_model_loc: 'prms_sntemp/20191002_Delaware_streamtemp'

pb_model_run_loc: '4_pb_model/tmp'

subbasin_outlet: '4182'

#lordville site is seg_id_nat == 1573; model_idx = 224; 1574 & 1575 are directly upstream of 1573 and 1577 is directly downstream of 1573
cur_seg_id_nat: ['1573']

project_id: 'da_pgdl_stream_temp_20201203'

# model states
states:
  state:
  - seg_tave_water
  - seg_tave_air
  - seg_tave_upstream
  - seg_tave_sroff
  - seg_tave_ss
  - seg_tave_gw
  - seg_rain
  - seg_outflow
  - seg_upstream_inflow
  - seginc_gwflow
  - seginc_potet
  - seginc_sroff
  - seginc_ssflow
  - seginc_swrad
  - seg_humid
  - seg_shade
  - seg_ccov
  - seg_width
  units:
  - degrees C
  - degrees C
  - degrees C
  - degrees C
  - degrees C
  - degrees C
  - meters
  - cms
  - cms
  - cms
  - meters
  - cms
  - cms
  - W m^-2
  - decimal fraction
  - decimal fraction
  - decimal fraction
  - meters
  longname:
  - Computed daily mean stream temperature for each segment
  - Area-weighted average air temperature for each segment from HRUs contributing flow to the segment
  - Temperature of streamflow entering each segment
  - surface runoff temperature
  - subsurface temperature
  - groundwater temperature
  - Area-weighted average rainfall for each segment from HRUs contributing flow to the segment
  - Streamflow leaving a segment
  - Sum of inflow from upstream segments
  - Area-weighted average groundwater discharge for each segment from HRUs contributing flow to the segment
  - Area-weighted average potential ET for each segment from HRUs contributing flow to the segment
  - Area-weighted average surface runoff for each segment from HRUs contributing flow to the segment
  - Area-weighted average interflow for each segment from HRUs contributing flow to the segment
  - Area-weighted average solar radiation for each segment from HRUs contributing flow to the segment
  - Area-weighted average relative humidity for each segment from HRUs contributing flow to the segment
  - Area-weighted average shade fraction for each segment
  - Area-weighted average cloud cover fraction for each segment from HRUs contributing flow to the segment
  - Width of each segment
  prec:
  - float
  - float
  - float
  - float
  - float
  - float
  - float
  - double
  - double
  - double
  - double
  - double
  - double
  - double
  - float
  - float
  - float
  - float

# model drivers
drivers:
  driver:
  - prcp
  - tmax
  - tmin
  units:
  - inches
  - degrees F
  - degrees F
  longname:
  - daily accumulated precipitation
  - maximum daily temperature
  - minimum daily temperature
  prec:
  - float
  - float
  - float

# model parameters
params:
  param:
  - ss_tau
  - gw_tau
  - albedo
  - melt_temp
  min:
  - 1.0
  - 10.0
  - 0.0
  - 0.0
  max:
  - 50.0
  - 150.0
  - 1.0
  - 10.0
  mean:
  - 6.0
  - 45.0
  - 0.1
  - 1.5
  sd:
  - 2.0
  - 6.0
  - .05
  - 1.0
  units:
  - days
  - days
  - decimal fraction
  - degrees C
  longname:
  - Average residence time of subsurface interflow
  - Average residence time in groundwater flow
  - Short-wave solar radiation reflected by streams
  - Temperature at which snowmelt enters a stream
  prec:
  - integer
  - integer
  - float
  - float

